name: Weltenbummlerpaar Frontend CI
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/base:18.12.0
      options: --user 1001
    env:
      WELTENBUMMLERPAAR_FRONTEND_API_BASE_URL: http://localhost:3000
      WELTENBUMMLERPAAR_FRONTEND_IMG_BASE_URL: http://localhost:3000/image-uploads
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm run test:unit
    - run: npm run test:component
    - run: npm run test:e2e
